### ISSUE TITLE
ベンチマーカーAMIの実装が古い

### ISSUE THREAD

**Issue by Muratam** [showwin/ISHOCON2#29]
https://github.com/showwin/ISHOCON2/blob/master/README.md の,
`ベンチマーカーAMI: ami-78b66107` を用意してくださっているのは大変ありがたいのですが,
ami-78b66107 のベンチマーカーは実装が古い段階のものであり,50000点くらいまでしか出ない(TLSハンドシェイクのため)ので,isuconの練習をする方が困るかもしれません.

そのため,ドキュメントのどこかに注記しておくか, ami を更新した方がisuconの練習をする方にむけては助かるかもしれません.

**Comment by showwin** [comment]
https://github.com/showwin/ISHOCON2/pull/34 にて修正
