### ISSUE TITLE
ベンチマーカーの http.Client に TLS handshake のタイムアウトが設定されていないことでベンチマークが hang することがある

### ISSUE THREAD

**Issue by astj** [showwin/ISHOCON2#32]
benchmarker では `http.Transport` を作る際に `TLSClientConfig` のみ設定していますが、

https://github.com/showwin/ISHOCON2/blob/8d8aae9509bcf32ce1e877b74e93ec8fa6c6cbcb/admin/benchmarker/request.go#L79-L81

この状態だと https://pkg.go.dev/net/http?tab=doc#Transport にあるように TLSHandshakeTimeout がゼロ値 = タイムアウトなしとなり、サーバー側が TLS handshake で詰まっているときに待ち続けてしまうようです。

高負荷のためうまく接続できないこと自体は競技者側の責任としてよいでしょうが、ベンチマーカーがそこで hang してしまうのは計測上問題があるのでなんらかのタイムアウトを設けるのが望ましいように思います。

通常の net/http のデフォルト挙動から変更する意図がなければ、 https://github.com/astj/ISHOCON2/commit/8bc05ca8c3202f067c5b404c0603fe706a342edf (`Transport#Clone` を使ってしまったのでおそらく >= Go 1.13 でしか動かないです) のように http.DefaultTransport の設定を clone すると穏当なタイムアウトが設定できるかと思います。
もちろん、 https://github.com/golang/go/blob/go1.15.1/src/net/http/transport.go#L42-L54 と同じ値を直接指定しても良くなるだろうと思っています。

**Comment by showwin** [comment]
@astj 解決策まで丁寧に提示いただきありがとうございます！
またISHOCON2で遊んでいただき大変うれしいです。

修正版のベンチマーカーのAMIを作成次第こちらのIssueをcloseさせていただきます。

**Comment by showwin** [comment]
https://github.com/showwin/ISHOCON2/pull/34 にて修正
