### ISSUE TITLE
CIで各言語実装に対してベンチマーカが通ることを確認したい

### ISSUE THREAD

**Issue by showwin** [showwin/ISHOCON2#40]
ライブラリや言語のバージョンの更新をしていきたいが、影響範囲を毎回調査するのはつらい。
初期実装でベンチマーカが通ればOKという条件で無条件にあげていけたら嬉しい。

**Comment by mickamy** [comment]
@showwin 
以下 PR にて、gh actions workflow を作成してみました（python 実装で落ちていますが...）
https://github.com/showwin/ISHOCON2/pull/54

**Comment by showwin** [comment]
@mickamy おかげさまでライブラリや言語のアップデートが捗ります 🙏 めちゃくちゃ助かりました！！
