### ISSUE TITLE
Apple Silicon 対応

### ISSUE THREAD

**Issue by mickamy** [showwin/ISHOCON2#56]
## 課題と解決方法

- 現在の app-base および benchmarker のイメージが、アーキテクチャの違いから、apple silicon mac で動かした場合にパフォーマンスが悪化する恐れがある
- arch が amd64 だった場合に arm64v8/ubuntu をベースイメージとすることで、パフォーマンスの改善が見込まれる
  - https://hub.docker.com/r/arm64v8/ubuntu/
- その場合にはローカルで app-base と benchmarker をビルド可能にする必要がある

## 懸念点

- private isucon という観点から言うと、イメージを変えるのは良くない可能性がある

**Comment by mickamy** [comment]
@showwin 

私の fork 先の PR ですが、このような形で対応してみました。
よろしければご確認ください。妥当な変更でしたら、こちらに PR を出したいと思います。

https://github.com/mickamy/ISHOCON2/pull/8

**Comment by showwin** [comment]
@mickamy ご提案ありがとうございます！
調査していただいた結果、パフォーマンスへの影響はほとんどなさそうなので変更の動機がパフォーマンスの悪化の懸念だけであれば今回はcloseさせていただこうかと思います 🙏

**Comment by mickamy** [comment]
@showwin 
issue のクローズについて、理解しました。
そうなると、以下の PR ですが、ベンチマーカを CI で動かせるようにするのと、php, crystal の実装の修正だけのものを新たに作成した方がよろしいでしょうか？

https://github.com/showwin/ISHOCON2/pull/60
https://github.com/showwin/ISHOCON2/pull/54
